/**
 * The four export targets (ticket 03).
 *
 * The central finding: a Tailwind v4 `@theme` block CANNOT hold a light/dark
 * pair -- theme variables must be top-level, never nested under a selector. So
 * the working shape is a three-part sandwich:
 *
 *   1. `:root` / `.dark` plain custom properties, which *can* vary by selector
 *   2. `@theme inline` bridging them into utility names
 *   3. `@custom-variant dark` replacing v3's `darkMode` config
 *
 * `inline` is mandatory, not stylistic: without it the utility emits
 * `var(--color-x)`, which resolves where it is DEFINED (`:root`), so a
 * subtree-scoped `.dark` silently fails.
 *
 * Because of that, the Tailwind and shadcn exports are ONE emitter with a
 * different name map, not two features.
 *
 * PURE: no DOM, no clock, no randomness.
 */

import { oklchToCss, oklchToHex } from "./oklch.ts";
import type { Palette, Role, Theme } from "./schema.ts";
import { ROLES } from "./schema.ts";
import { getCharacter } from "./characters.ts";

export type ExportFormat = "globals" | "theme" | "plain" | "json";

export interface ExportTarget {
  readonly id: ExportFormat;
  readonly filename: string;
  readonly language: string;
  readonly label: string;
  readonly description: string;
}

export const EXPORT_TARGETS: readonly ExportTarget[] = [
  {
    id: "globals",
    filename: "globals.css",
    language: "css",
    label: "shadcn / globals.css",
    description: "Drop-in replacement for a shadcn project's globals.css. Exact shadcn token names.",
  },
  {
    id: "theme",
    filename: "theme.css",
    language: "css",
    label: "Tailwind v4 theme",
    description: "Same machinery, our own role names, including success, warning and link.",
  },
  {
    id: "plain",
    filename: "palette.css",
    language: "css",
    label: "Plain CSS",
    description: "No Tailwind. light-dark() plus color-scheme, so system default needs no JavaScript.",
  },
  {
    id: "json",
    filename: "palette.json",
    language: "json",
    label: "JSON tokens",
    description: "Machine-readable, and the only format that round-trips back into this tool.",
  },
];

/** shadcn omits these; they are ours. Emitted in theme.css and palette.css only. */
const NON_SHADCN: readonly Role[] = [
  "success",
  "success-foreground",
  "warning",
  "warning-foreground",
  "link",
  "destructive-foreground",
];

const shadcnRoles = ROLES.filter((r) => !NON_SHADCN.includes(r));

function header(palette: Palette): string {
  const char = getCharacter(palette.character);
  const bodyFloor = palette.contrastMode === "strict" ? "Lc 90" : "Lc 75";
  const note =
    palette.contrastMode === "strict"
      ? "safe at 16px / weight 400"
      : "requires >= 18px/400, 16px/500 or 14px/700";

  return `/* Generated by Palette Creator -- https://github.com/MTBasso/palette-creator
 *
 * Seed         ${palette.seed}
 * Character    ${char.name} (${char.id})
 * Contrast     ${palette.contrastMode} -- body text ${bodyFloor}, ${note}
 *
 * Every guaranteed pairing clears BOTH floors:
 *   APCA (apca-w3, algorithm 0.0.98G-4g) and WCAG 2.x contrast ratio.
 * The binding constraint differs by theme, which is why both are enforced.
 *
 * This is not a claim of legibility for every reader on every screen. No
 * two-colour metric models that. Body text is assumed to be ${palette.contrastMode === "strict" ? "16px / 400" : ">= 18px / 400"};
 * a smaller or lighter face falls below the assumption regardless of these values.
 */`;
}

function block(palette: Palette, theme: Theme, roles: readonly Role[], indent = "  "): string {
  return roles
    .map((role) => `${indent}--${role}: ${oklchToCss(palette.tokens[role][theme])};`)
    .join("\n");
}

/* -------------------------------------------------------------------------- */

function emitTailwindStyle(palette: Palette, roles: readonly Role[]): string {
  const bridge = roles.map((r) => `  --color-${r}: var(--${r});`).join("\n");

  return `${header(palette)}

@import "tailwindcss";

/* Replaces v3's darkMode config. :where() keeps specificity at zero, and unlike
   shadcn's &:is(.dark *) it also matches the themed element itself. */
@custom-variant dark (&:where(.dark, .dark *));

:root {
  color-scheme: light;
  --radius: 0.625rem;
${block(palette, "light", roles)}
}

.dark {
  color-scheme: dark;
${block(palette, "dark", roles)}
}

/* "inline" is required. Without it the utility emits var(--color-x), which
   resolves where it is defined -- in :root -- so a scoped .dark never applies. */
@theme inline {
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
${bridge}
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`;
}

function emitPlain(palette: Palette): string {
  const pairs = ROLES.map((role) => {
    const light = oklchToHex(palette.tokens[role].light);
    const dark = oklchToHex(palette.tokens[role].dark);
    return `  --${role}: light-dark(${light}, ${dark});`;
  }).join("\n");

  const raw = ROLES.map((role) => {
    const light = oklchToHex(palette.tokens[role].light);
    const dark = oklchToHex(palette.tokens[role].dark);
    return `  --${role}-light: ${light};\n  --${role}-dark: ${dark};`;
  }).join("\n");

  return `${header(palette)}

/* Three theme states with no JavaScript and no media query:
 *   [data-theme="light"] / [data-theme="dark"] force a theme,
 *   and the bare :root follows the operating system.
 *
 * light-dark() resolves against color-scheme, so color-scheme is the switch.
 * Caveat: because CSS has no selector for "the used colour-scheme is dark",
 * this pattern is invisible to Tailwind's dark: variant -- use theme.css there.
 * It is also opaque to getComputedStyle, so JS token readers want the raw
 * --<role>-light / --<role>-dark values below.
 */

:root {
  color-scheme: light dark;
${pairs}
}

:root[data-theme="light"] {
  color-scheme: light;
}

:root[data-theme="dark"] {
  color-scheme: dark;
}

/* Raw values, for tooling that cannot see through light-dark(). */
:root {
${raw}
}

body {
  background: var(--background);
  color: var(--foreground);
}
`;
}

function emitJson(palette: Palette): string {
  const tokens: Record<string, { light: string; dark: string; lightOklch: string; darkOklch: string }> = {};
  for (const role of ROLES) {
    tokens[role] = {
      light: oklchToHex(palette.tokens[role].light),
      dark: oklchToHex(palette.tokens[role].dark),
      lightOklch: oklchToCss(palette.tokens[role].light),
      darkOklch: oklchToCss(palette.tokens[role].dark),
    };
  }

  return JSON.stringify(
    {
      $schema: "https://github.com/MTBasso/palette-creator",
      generator: "palette-creator",
      version: 1,
      input: {
        seed: palette.seed,
        character: palette.character,
        contrastMode: palette.contrastMode,
      },
      assumptions: {
        bodyText: palette.contrastMode === "strict" ? "16px/400" : ">=18px/400",
        apcaAlgorithm: "0.0.98G-4g",
        enforced: ["APCA", "WCAG 2.x"],
      },
      tokens,
    },
    null,
    2,
  );
}

export function exportPalette(palette: Palette, format: ExportFormat): string {
  switch (format) {
    case "globals":
      return emitTailwindStyle(palette, shadcnRoles);
    case "theme":
      return emitTailwindStyle(palette, ROLES);
    case "plain":
      return emitPlain(palette);
    case "json":
      return emitJson(palette);
  }
}

/** CSS custom properties for the live preview, as a style object. */
export function cssVariables(palette: Palette, theme: Theme): Record<string, string> {
  const vars: Record<string, string> = {};
  for (const role of ROLES) {
    vars[`--${role}`] = oklchToHex(palette.tokens[role][theme]);
  }
  return vars;
}
